### ISSUE TITLE
How Should I Run It

### ISSUE THREAD

**Issue by SpreadSheets650** [Yashar-Nishaburi/POKE-BOT#3]
#  Hey, Thank You For The AutoCatcher. #

```But i am using repel.it to run it i just wanted to know what command should i use to start it.```

**Comment by Yashar-Nishaburi** [comment]
Not very familiar with repelit but as far as I'm aware the script wont work with in-browser IDEs. Easiest way to run it is with the default python IDE. Don't forget to pip install discord.py!
